rpmcpio.c: fixed the rpm.org commit reference
It turns out rpm cannot even install rpms with symlinked hardlinks.
In rpm-4.6.0-rc1~93, they call them "broken cpio" and the like.
This makes my job much easier I guess.

$ cat ~RPM/SPECS/hardsymlinks.spec
Name: hardsymlinks
Version: 1.0
Release: 0
Summary: Contains hardlinked symlinks
License: GPL
Group: System
%description
%install
mkdir -p %buildroot%_datadir
cd %buildroot%_datadir
echo foo >a
ln -s a b
ln b c
%files
%_datadir/*

$ sudo rpm -iv ~/RPM/RPMS/x86_64/hardsymlinks-1.0-0.x86_64.rpm
Preparing packages...
hardsymlinks-1.0-0.x86_64
error: unpacking of archive failed: cpio: Bad magic
error: hardsymlinks-1.0-0.x86_64: install failed